[package]
name = "low_level"
version = "0.1.0"
edition = "2021"

[profile.release]
lto = true

[lib]
crate-type = ["staticlib"]

[dependencies]
anyhow = "1.0"
cpal = "0.15"
env_logger = "0.10"
hound = "3.5"
log = "0.4"
ocaml = "0.22"
