name: test
on:
  push:
    branches:
    - '*'
env:
  CARGO_TERM_COLOR: always

jobs:
  build-and-run-tests:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macOS-latest]
    steps:
    - uses: actions/checkout@v3
    - uses: hecrj/setup-rust-action@v1
      with:
        rust-version: stable
    - name: Set-up OCaml
      uses: ocaml/setup-ocaml@v2
      with:
        ocaml-compiler: "4.14.1"
    - run: opam install . --deps-only --with-test
    - run: opam exec -- dune build
    - run: opam exec -- dune runtest
    - run: opam exec -- dune build -p llama_core
    - run: opam exec -- dune build -p llama
    - run: opam exec -- dune build -p llama_interactive

  test-packaging-script:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macOS-latest]
    steps:
    - uses: actions/checkout@v3
    - uses: hecrj/setup-rust-action@v1
      with:
        rust-version: stable
    - name: 'Vendor Rust Dependencies'
      run: scripts/switch-to-vendored-rust.sh
    - name: 'Create release artifact'
      run: |
        tar -czf /tmp/llama.tar.gz --exclude=.git -C .. llama
        mkdir /tmp/empty
        cd /tmp/empty
    - if: matrix.os == 'ubuntu-latest'
      name: Set-up OCaml
      uses: ocaml/setup-ocaml@v2
      with:
        ocaml-compiler: "4.14.1"
        opam-depext-flags: ocamlsdl2,conf-alsa
    - if: matrix.os == 'macOS-latest'
      name: Set-up OCaml
      uses: ocaml/setup-ocaml@v2
      with:
        ocaml-compiler: "4.14.1"
        opam-depext-flags: ocamlsdl2
    - run: opam pin /tmp/llama.tar.gz
