name: test
on:
  push:
    branches:
    - '*'
env:
  CARGO_TERM_COLOR: always

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: hecrj/setup-rust-action@v1
      with:
        rust-version: stable
    - name: Set-up OCaml
      uses: ocaml/setup-ocaml@v2
      with:
        ocaml-compiler: "4.14.1"
    - run: opam install . --deps-only --with-test
    - run: opam install -y ocamlsdl2
    - run: opam exec -- dune build
    - run: opam exec -- dune runtest
